version: '3'

services:
  app:
    profiles: ['devcontainer']
    container_name: go-study
    image: mcr.microsoft.com/devcontainers/go:1.22-bullseye
    volumes:
      - .:/workspace:cached
    stdin_open: true
    tty: true
    environment:
      DEVCONTAINER: 1
    network_mode: host